version: "2"

services: 
  fish_shop_backend:
    container_name: backend
    image: fish_shop_backend
    build: .
    ports:
      - '80:80'
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.0
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data:/var/lib/postgresql/data