# Generated by Django 4.2.6 on 2023-11-14 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='addition_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время добавления товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара'),
            preserve_default=False,
        ),
    ]
