# Generated by Django 4.2.6 on 2023-11-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_addition_datetime_products_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchase_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано единиц товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара в наличии'),
        ),
    ]
