# Generated by Django 4.2.6 on 2023-11-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Скидка, %'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка, %'),
        ),
    ]
