# Generated by Django 4.2.6 on 2023-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_discount_products_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, verbose_name='Описание скидки'),
        ),
    ]
