# Generated by Django 4.2.6 on 2023-11-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_to_datetime_discount_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
