# Generated by Django 4.2.6 on 2023-11-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_alter_discount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Скидка'),
        ),
    ]
