# Generated by Django 4.2.6 on 2023-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='addition_datetime',
            field=models.DateTimeField(editable=False, verbose_name='Дата и время добавления товара'),
        ),
    ]
