# Generated by Django 4.2.6 on 2023-12-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_addition_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
